#
#  YAML File to configure the Gazebo controllers
#
#  These parameters support the various controllers.  They include the
#  six DOFS for the sixDOF robot.
#
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controller:
  ros__parameters:
    joints:
      - theta1
      - theta2
      - theta3
      - theta4
      - theta5
      - theta6
    state_interfaces:
      - position
      - velocity
      - effort
    command_interfaces:
      - effort

velocity_controller:
  ros__parameters:
    joints:
      - theta1
      - theta2
      - theta3
      - theta4
      - theta5
      - theta6
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

position_controller:
  ros__parameters:
    joints:
      - theta1
      - theta2
      - theta3
      - theta4
      - theta5
      - theta6
    state_interfaces:
      - position
    command_interfaces:
      - position
